$(function(){
	$(".content").hide();
	$(".navbar-main").hover(function(){
		$(".content").show();
		$(".navbar-bg").css("background","#2f69a3")
	},function(){
		$(".content").hide();
		$(".navbar-bg").css("background","#fff")
	});	
})